export type EventType = "gift-qa" | "quiz" | "survey" | "wheel" | "interactive";

export type CatalogEvent = {
  slug: string;
  title: string;
  type: EventType;
  companyName: string;
  topic: string;
  date: string;
  startTime: string;
  endTime: string;
  location: string;
  description: string;
  gift: string;
  config: unknown;
};

export const PAVILION_EVENTS: CatalogEvent[] = [
  {
    slug: "amr-hediyeli-quiz",
    title: "Mikrobiyal direnç hediyeli soru-cevap",
    type: "gift-qa",
    companyName: "Astorg (Thermo Fisher)",
    topic: "Mikrobiyal direnç",
    date: "2026-11-09",
    startTime: "10:00",
    endTime: "17:00",
    location: "Stant A — Astorg",
    description: "İklim ve antibiyotik direnci üzerine 3 soru. Doğru yanıtlayanlar tohum kalem ve AMR kartına girer.",
    gift: "Tohum kalem + AMR infografik kart",
    config: {
      passScore: 2,
      questions: [
        { q: "Sıcaklık artışı neden antimikrobiyal direnci hızlandırır?", options: ["Bakteri üremesini ve yayılımı kolaylaştırır", "Antibiyotikleri yok eder", "Aşıları etkisiz kılar"], answer: 0 },
        { q: "Doğru antibiyotik kullanımı için hangisi doğrudur?", options: ["Ateş olunca hemen geniş spektrum", "Hekim önerisi ve tam kür", "Komşunun ilacını paylaşmak"], answer: 1 },
        { q: "Sağlık pavilionunda AMR farkındalığının amacı nedir?", options: ["Sadece satış", "İklim-sağlık bağını göstermek", "Laboratuvar kurulumu"], answer: 1 },
      ],
    },
  },
  {
    slug: "koah-nefes-anketi",
    title: "KOAH ve iklim — nefes anketi",
    type: "survey",
    companyName: "Sanofi TR",
    topic: "KOAH",
    date: "2026-11-09",
    startTime: "11:00",
    endTime: "18:00",
    location: "Seminer Salonu",
    description: "Solunum sağlığı ve hava kirliliği farkındalık anketi. Katılanlara küçük hediye.",
    gift: "Nefes egzersizi kartı + Sanofi broşür",
    config: {
      questions: [
        { q: "Hava kirliliği solunum şikayetlerinizi etkiler mi?", options: ["Evet, sık", "Bazen", "Hayır", "Emin değilim"] },
        { q: "KOAH riskini artıran iklim etkisi hangisi?", options: ["Toz ve sıcak dalgası", "Sadece soğuk", "Yağmur"] },
        { q: "Bugün pavilon mesajından ne götürüyorsunuz?", options: ["Korunma", "Tedavi erişimi", "Her ikisi"] },
      ],
    },
  },
  {
    slug: "asi-bilgi-yarismasi",
    title: "Aşı ve salgın bilgi yarışması",
    type: "quiz",
    companyName: "AstraZeneca TR / Berko İlaç",
    topic: "Aşı",
    date: "2026-11-10",
    startTime: "10:00",
    endTime: "17:00",
    location: "Seminer Salonu",
    description: "İklim, salgın ve aşılama üzerine puanlı yarışma. Yüksek puan hediye çeker.",
    gift: "Aşı takvimi magnet + su matarası (çekiliş)",
    config: {
      passScore: 2,
      questions: [
        { q: "İklim krizi yeni salgın riskini nasıl etkiler?", options: ["Vektörlerin coğrafyasını genişletir", "Etkilemez", "Sadece grip azaltır"], answer: 0 },
        { q: "Toplum bağışıklığı için kritik olan nedir?", options: ["Tek doz herkese yeter", "Yüksek ve adil aşı kapsaması", "Sadece risk grupları"], answer: 1 },
        { q: "Paviliondaki aşı mesajı kime yönelik?", options: ["Yalnızca çocuklar", "Tüm yaş grupları ve gezginler", "Sadece sağlıkçılar"], answer: 1 },
      ],
    },
  },
  {
    slug: "karbon-kilo-carki",
    title: "Karbon & BMI dijital çark",
    type: "wheel",
    companyName: "Novo Nordisk TR",
    topic: "Halk sağlığı koruma",
    date: "2026-11-11",
    startTime: "10:00",
    endTime: "18:00",
    location: "Deneyim Alanı",
    description: "Çarkı çevir, sağlık-iklim ipucu veya hediye kazan. Interaktif karbon-kilo farkındalığı.",
    gift: "Adım sayar bileklik / meyve atıştırmalık / karbon kartı",
    config: {
      slices: [
        { label: "Tohum kalem", prize: "Tohum kalem", color: "#0077C2" },
        { label: "Karbon kartı", prize: "Kişisel karbon ipucu kartı", color: "#22A34A" },
        { label: "Atıştırmalık", prize: "Sağlıklı atıştırmalık", color: "#00A3E0" },
        { label: "Tekrar çevir", prize: "Tekrar çevir hakkı", color: "#1F4E5F" },
        { label: "Adım bilekliği", prize: "Adım sayar (sınırlı)", color: "#5C4E7A" },
        { label: "Su matarası", prize: "Cam/metal matara kuponu", color: "#3D5A4C" },
      ],
    },
  },
  {
    slug: "yesil-uretim-anketi",
    title: "Yeşil ilaç üretimi anketi",
    type: "survey",
    companyName: "World Medicine / Humanis",
    topic: "Karbon ayak izini azaltan üretim",
    date: "2026-11-10",
    startTime: "09:00",
    endTime: "18:00",
    location: "Networking / Kahve",
    description: "İlaç üretiminde karbon azaltımı algı anketi. Kahve ikramı ile birlikte.",
    gift: "Kahve + üretim infografiği",
    config: {
      questions: [
        { q: "Bir ilacın karbon ayak izini hiç düşündünüz mü?", options: ["Evet", "Hayır", "İlk kez burada"] },
        { q: "Hangisi yeşil üretimi en çok etkiler?", options: ["Enerji kaynağı", "Ambalaj", "Lojistik", "Hepsi"] },
        { q: "Kahve istasyonunda hangi mesaj kaldı?", options: ["Döngüsel ambalaj", "Yenilenebilir enerji", "İkisi"] },
      ],
    },
  },
  {
    slug: "iot-tisort-deneyimi",
    title: "IoT tişört solunum deneyimi",
    type: "interactive",
    companyName: "Ertunç Özcan",
    topic: "Dijital solunum izleme",
    date: "2026-11-11",
    startTime: "10:00",
    endTime: "17:00",
    location: "Stant F — Deneyim",
    description: "30 saniyelik dijital solunum gösterimi. Uzaktan takip ve karbon azaltımı anlatılır.",
    gift: "IoT demo rozeti",
    config: {
      steps: [
        { title: "1. Ölç", body: "Tişört sensoru ile nefes ritmini izleyin (demo)." },
        { title: "2. Anlam", body: "Uzaktan izleme yaşlı bakımında seyahat ve kâğıt israfını azaltır." },
        { title: "3. İklim bağı", body: "Daha az gereksiz başvuru = daha düşük karbon." },
      ],
    },
  },
  {
    slug: "solunum-iklim-quiz",
    title: "Solunum yolu hastalıkları — iklim quizi",
    type: "gift-qa",
    companyName: "Atabay İlaç",
    topic: "Solunum yolu hastalıkları",
    date: "2026-11-12",
    startTime: "10:00",
    endTime: "16:00",
    location: "Stant C — Atabay",
    description: "İklim riski ve solunum sağlığı hediyeli soru-cevap.",
    gift: "Cep nebulizatör bilgi kartı + eşantiyon",
    config: {
      passScore: 2,
      questions: [
        { q: "Sıcak dalgası astım/KOAH ataklarını nasıl etkiler?", options: ["Artırır", "Azaltır", "İlgisiz"], answer: 0 },
        { q: "Toz ve polen mevsiminin uzaması neye bağlıdır?", options: ["İklim değişikliği", "Sadece genetik", "Tesadüf"], answer: 0 },
        { q: "Paviliondaki doğru mesaj?", options: ["Erken tanı + temiz hava", "Sadece ilaç", "Bekle-gör"], answer: 0 },
      ],
    },
  },
  {
    slug: "kagit-israfi-carki",
    title: "Teleradyoloji — kâğıt israfı çarkı",
    type: "wheel",
    companyName: "Yinwest Startups",
    topic: "Teleradyoloji ile kâğıt israfının önlenmesi",
    date: "2026-11-14",
    startTime: "11:00",
    endTime: "17:00",
    location: "Startup Köşesi",
    description: "Dijital film vs kâğıt. Çarkı çevir, gençlik hediyesi kap.",
    gift: "USB / tohum kart / sticker",
    config: {
      slices: [
        { label: "Tohum kart", prize: "Tohum kart", color: "#22A34A" },
        { label: "Sticker", prize: "Dijital sağlık sticker", color: "#0077C2" },
        { label: "USB", prize: "Geri dönüştürülmüş USB", color: "#1F4E5F" },
        { label: "Tekrar", prize: "Tekrar çevir", color: "#00A3E0" },
        { label: "Rozet", prize: "Gençlik elçisi rozeti", color: "#5C4E7A" },
        { label: "Teşekkür", prize: "Dijital teşekkür sertifikası", color: "#3D5A4C" },
      ],
    },
  },
  {
    slug: "afet-saglik-kabini",
    title: "Afetlerde mobil sağlık kabini — interaktif tur",
    type: "interactive",
    companyName: "Dilek Hanım",
    topic: "Seyyar atık dönüşümü ve mobil sağlık",
    date: "2026-11-15",
    startTime: "10:00",
    endTime: "18:00",
    location: "Deneyim Alanı",
    description: "Afet senaryosunda 3 adımlı interaktif tur. Karbon ve hijyen mesajı.",
    gift: "Mini ilk yardım kartı",
    config: {
      steps: [
        { title: "Senaryo", body: "Sel sonrası sahada mobil kabin kurulur." },
        { title: "Hijyen", body: "Atık su dönüşümü olmadan salgın riski artar." },
        { title: "İklim", body: "Tekrar kullanılabilir kabin, tek kullanımlık kamp israfını keser." },
      ],
    },
  },
];

export const SOLAKLAR_EVENTS: CatalogEvent[] = [
  {
    slug: "solaklar-11-karsilama-cemberi",
    title: "Solaklar açık hava karşılama çemberi",
    type: "interactive",
    companyName: "SGGM · Sıfır Atık Köyü",
    topic: "Sıfır atık · Liderler Zirvesi 1. Gün",
    date: "2026-11-11",
    startTime: "08:30",
    endTime: "09:20",
    location: "Solaklar Köyü — giriş meydanı",
    description: "Günlük güvenlik, sıfır atık kuralı ve güzergâh brifingi. Tek kullanımlık yok; matara ve bez çanta.",
    gift: "Bez çanta + köy haritası",
    config: {
      steps: [
        { title: "Karşılama", body: "Elçiler ziyaretçiyi meydanda karşılar, QR ile kayıt alır." },
        { title: "Kurallar", body: "Köyde pet şişe ve tek kullanımlık tabak yok. Atık üç kutuya ayrılır." },
        { title: "Güzergâh", body: "Sabah yürüyüşü → kompost → öğle molası → öğleden sonra lider durakları." },
      ],
    },
  },
  {
    slug: "solaklar-11-sifir-atik-yuruyusu",
    title: "Sıfır Atık Köyü açık hava yürüyüşü",
    type: "interactive",
    companyName: "SGGM · Sıfır Atık Köyü",
    topic: "Döngüsel ekonomi sahada",
    date: "2026-11-11",
    startTime: "09:30",
    endTime: "11:00",
    location: "Solaklar — köy içi güzergâh (yaklaşık 1,2 km)",
    description: "Beş açık hava durağı: evsel ayrıştırma, yağmur suyu, kompost, onarım tezgâhı, ortak fırın/imece.",
    gift: "Yürüyüş kartı (damgalı)",
    config: {
      steps: [
        { title: "Durak 1 — Ayrıştırma", body: "Organik / ambalaj / cam. Sağlık atığı köye sokulmaz." },
        { title: "Durak 2 — Su", body: "Yağmur oluğu ve matara dolum noktası; pet yasak." },
        { title: "Durak 3 — Toprak", body: "Kompostun gıda ve yerel tarıma dönüşü." },
        { title: "Durak 4 — Onarım", body: "Tamir etmek yeni ürün almaktan düşük karbonludur." },
        { title: "Durak 5 — İmece", body: "Ortak fırın / gölgelik; topluluk sağlığı." },
      ],
    },
  },
  {
    slug: "solaklar-11-kompost-istasyonu",
    title: "Kompost ve toprak sağlığı istasyonu",
    type: "survey",
    companyName: "SGGM · yerel üretici",
    topic: "Organik döngü · gıda-sağlık",
    date: "2026-11-11",
    startTime: "11:00",
    endTime: "12:20",
    location: "Solaklar — bahçe / kompost alanı",
    description: "Açık havada kompost dokunma istasyonu. Gıda israfı ve toprak mikrobu-sağlık bağı anlatılır.",
    gift: "Küçük kompost çayı / tohum kâğıdı",
    config: {
      questions: [
        { q: "Mutfak atığınızı bugün nasıl değerlendirirsiniz?", options: ["Kompost", "Çöp", "Hayvan yemi", "Bilmiyorum"] },
        { q: "Sağlıklı toprak neden halk sağlığıdır?", options: ["Gıda besin değeri", "Sadece tarım işi", "İlgisiz"] },
        { q: "Köyde pet şişe yerine ne kullanıyoruz?", options: ["Matara / cam", "Tek kullanımlık", "Poşet"] },
      ],
    },
  },
  {
    slug: "solaklar-11-sifir-atik-ogle",
    title: "Paketsiz açık hava öğle molası",
    type: "survey",
    companyName: "SGGM",
    topic: "Sıfır atık ikram protokolü",
    date: "2026-11-11",
    startTime: "12:30",
    endTime: "13:30",
    location: "Solaklar — gölgelik / zeytin altı",
    description: "Tek kullanımlıksız ikram. Yerel mevsim ürünü. Lider ziyareti öncesi saha sessizlik kuralı hatırlatılır.",
    gift: "Yeniden kullanılabilir peçete / ahşap çatal hatırası",
    config: {
      questions: [
        { q: "Öğle molasında tek kullanımlık gördünüz mü?", options: ["Hayır", "Evet", "Emin değilim"] },
        { q: "Yerel ürün yemek karbonu nasıl etkiler?", options: ["Düşürür", "Artırır", "Fark etmez"] },
      ],
    },
  },
  {
    slug: "solaklar-11-lider-guzergahi",
    title: "Üst düzey ziyaret açık hava güzergâhı",
    type: "interactive",
    companyName: "SGGM Protokol",
    topic: "Liderler Zirvesi · sıfır atık köyü",
    date: "2026-11-11",
    startTime: "14:00",
    endTime: "15:20",
    location: "Solaklar — protokol durakları (meydan, bahçe, bakı noktası)",
    description: "Olası üst düzey / dünya lideri köy turu için açık hava durakları. Elçiler kenarda yönlendirir, foto hattı tek taraflı.",
    gift: "Protokol rozeti (görevli) / ziyaretçi damgası",
    config: {
      steps: [
        { title: "Meydan", body: "Kısa karşılama, sıfır atık mesajı, 4 dakika." },
        { title: "Bahçe", body: "Kompost ve yerel üretim; çeviri elçileri arkada durur." },
        { title: "Bakı", body: "Köy-doğa silüeti; kalabalık yol kenarında, patika açık." },
      ],
    },
  },
  {
    slug: "solaklar-11-ayristirma-oyunu",
    title: "Açık hava atık ayırma yarışı",
    type: "gift-qa",
    companyName: "SGGM · gençlik",
    topic: "Sıfır atık oyunlaştırma",
    date: "2026-11-11",
    startTime: "15:30",
    endTime: "16:30",
    location: "Solaklar — meydan çimi",
    description: "3 soruluk hediyeli yarışma + fiziksel ayırma istasyonu. Çocuk ve genç grupları.",
    gift: "Tohum topu + bez keseli hediye",
    config: {
      passScore: 2,
      questions: [
        { q: "Elma posası hangi kutuya gider?", options: ["Organik / kompost", "Ambalaj", "Cam"], answer: 0 },
        { q: "Tek kullanımlık bardak köy kuralına uygun mu?", options: ["Hayır", "Evet", "Sadece VIP’e"], answer: 0 },
        { q: "En düşük karbonlu su hangisi?", options: ["Matara + köy çeşmesi", "Pet şişe", "Poşet su"], answer: 0 },
      ],
    },
  },
  {
    slug: "solaklar-11-nefes-yuruyusu",
    title: "Gün sonu nefes ve gölge yürüyüşü",
    type: "interactive",
    companyName: "SGGM",
    topic: "İklim ve solunum sağlığı",
    date: "2026-11-11",
    startTime: "16:45",
    endTime: "17:45",
    location: "Solaklar — zeytin / tarla kenarı parkuru",
    description: "Yavaş tempo açık hava yürüyüşü. Sıcaklık, gölge ve temiz hava mesajı; Atabay/Sanofi solunum temasıyla uyumlu.",
    gift: "Nefes egzersizi kartı",
    config: {
      steps: [
        { title: "Isınma", body: "3 dakika gölgede nefes; su molası." },
        { title: "Parkur", body: "Gölgeli patika, tozlu yoldan kaçınılır." },
        { title: "Kapanış", body: "Neden kırsal gölgelik kent sağlığı için örnek?" },
      ],
    },
  },
  {
    slug: "solaklar-12-direnc-brifing",
    title: "Dirençli yerleşim açık hava brifingi",
    type: "interactive",
    companyName: "SGGM",
    topic: "Dirençli şehirler ve yapılı çevre — 2. Gün",
    date: "2026-11-12",
    startTime: "08:30",
    endTime: "09:20",
    location: "Solaklar — gölgelik brifing çemberi",
    description: "Sel, sıcak dalgası ve suyu köy ölçeğinde okuma. Liderler Günü 2 için saha notu.",
    gift: "Köy direnç haritası",
    config: {
      steps: [
        { title: "Su", body: "Yağmur hasadı ve taşkın yatağına yapı yasağı." },
        { title: "Sıcak", body: "Zeytin gölgesi = doğal klima." },
        { title: "Topluluk", body: "İmece, afet sonrası ilk 24 saatte sağlık korur." },
      ],
    },
  },
  {
    slug: "solaklar-12-doga-cozum-yuruyusu",
    title: "Doğa temelli çözüm yürüyüşü",
    type: "interactive",
    companyName: "SGGM",
    topic: "Nature-based solutions · halk sağlığı",
    date: "2026-11-12",
    startTime: "09:30",
    endTime: "11:00",
    location: "Solaklar — dere / tarla / gölge hattı",
    description: "Açık hava: taşkın çayırı, gölge ağaçları, geçirgen zemin. Kent hastanesi bahçelerine taşınabilir dersler.",
    gift: "NbS durak kartı",
    config: {
      steps: [
        { title: "Dere kenarı", body: "Beton kanal yerine bitkili tampon şerit." },
        { title: "Gölge", body: "Ağaç altı sıcaklığı 4–8° düşürür; yaşlı ve çocuk için kritik." },
        { title: "Zemin", body: "Geçirgen toprak sel yükünü keser." },
      ],
    },
  },
  {
    slug: "solaklar-12-sicaklik-istasyonu",
    title: "Açık hava sıcaklık, su ve hava istasyonu",
    type: "survey",
    companyName: "SGGM · sağlık",
    topic: "Sıcak dalgası ve hidrasyon",
    date: "2026-11-12",
    startTime: "11:00",
    endTime: "12:20",
    location: "Solaklar — gölgelik sağlık çadırı (açık yanlar)",
    description: "Termometre, matara dolumu, gölge molası. Anketle farkındalık; elçiler kayıt toplar.",
    gift: "Tuz-mineral kartı + matara dolumu",
    config: {
      questions: [
        { q: "Bugün gölgede mola verdiniz mi?", options: ["Evet", "Hayır"] },
        { q: "Sıcak günde ilk önlem?", options: ["Su + gölge", "Klima kovalamaca", "Kafein"] },
        { q: "Kırılgan grup?", options: ["Çocuk, yaşlı, kronik hasta", "Sadece sporcular", "Kimse"] },
      ],
    },
  },
  {
    slug: "solaklar-12-imece-bahce",
    title: "İmece: tohum ve aromatik bitki bahçesi",
    type: "interactive",
    companyName: "SGGM · yerel üretici",
    topic: "Yerel bilgi · gıda ve sağlık",
    date: "2026-11-12",
    startTime: "13:30",
    endTime: "15:00",
    location: "Solaklar — ortak bahçe",
    description: "Açık havada kekik, adaçayı, nane; tohum takası. İlaç değil, gıda ve gölge bitkisi anlatılır.",
    gift: "Yerel tohum paketi",
    config: {
      steps: [
        { title: "Tanı", body: "Üç aromatik bitki; güneş ve su ihtiyacı." },
        { title: "Takas", body: "Tohum paylaşımı, plastik kutu yok — kâğıt zarf." },
        { title: "Sağlık notu", body: "Bitki çayı hekim yerine geçmez; gıda çeşitliliği güçlendirir." },
      ],
    },
  },
  {
    slug: "solaklar-12-sifir-atik-carki",
    title: "Solaklar açık hava hediye çarkı",
    type: "wheel",
    companyName: "SGGM",
    topic: "Sıfır atık hediye",
    date: "2026-11-12",
    startTime: "15:15",
    endTime: "16:30",
    location: "Solaklar — meydan",
    description: "Dijital çark; hediyeler tek kullanımlıksız (tohum, bez, ahşap).",
    gift: "Tohum / bez çanta / ahşap rozet",
    config: {
      slices: [
        { label: "Tohum topu", prize: "Tohum topu", color: "#22A34A" },
        { label: "Bez çanta", prize: "Küçük bez kesesi", color: "#0077C2" },
        { label: "Ahşap rozet", prize: "Ahşap sıfır atık rozeti", color: "#00A3E0" },
        { label: "Matara dolum", prize: "Matara dolum + teşekkür", color: "#1F4E5F" },
        { label: "Tekrar", prize: "Tekrar çevir", color: "#5C4E7A" },
        { label: "Nane fidesi", prize: "Nane fidesi (sınırlı)", color: "#3D5A4C" },
      ],
    },
  },
  {
    slug: "solaklar-12-kapanis-halkasi",
    title: "Kapanış halkası ve teşekkür yürüyüşü",
    type: "survey",
    companyName: "SGGM",
    topic: "Liderler Zirvesi 2. Gün kapanış",
    date: "2026-11-12",
    startTime: "16:45",
    endTime: "17:45",
    location: "Solaklar — meydan",
    description: "İki günün öğrenilenleri. Ziyaretçi ve elçi geri bildirimi; alan temizliği imece.",
    gift: "Katılım damgası (dijital + kart)",
    config: {
      questions: [
        { q: "Köyden evinize hangi kuralı götürüyorsunuz?", options: ["Matara", "Kompost", "Gölge molası", "Hepsi"] },
        { q: "Yarın kentte uygulayabileceğiniz bir şey?", options: ["Tek kullanımlığı reddetmek", "Ağaç/gölge savunmak", "İkisi"] },
        { q: "Elçi desteği nasıldı?", options: ["Çok iyi", "İyi", "Gelişmeli"] },
      ],
    },
  },
];

export const EVENT_CATALOG: CatalogEvent[] = [...PAVILION_EVENTS, ...SOLAKLAR_EVENTS];

